name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

   - name: Train Model and Update Repository
  run: |
    echo "Treinando o modelo..."
    python notebooks/sales_prediction.ipynb
    git add modelos/modelo_regressao_linear.joblib
    git commit -m "Atualizar modelo de regressão linear"
    git push

    - name: Model Testing
      run: |
        echo "Executando testes no modelo..."
       
    - name: Deploy Model
      run: |
        echo "Implantando o modelo..."
      

